import io
from datetime import datetime, date
from typing import List, Optional
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Flowable,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from app.models.models import Report

class NumberedCanvas(canvas.Canvas):
    """Custom canvas to generate dynamic footer page numbers (Page X of Y) and header rules."""
    def __init__(self, *args, report=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.report = report
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Colors
        slate_900 = colors.HexColor("#1E293B")
        slate_500 = colors.HexColor("#64748B")
        blue_600 = colors.HexColor("#2563EB")
        border_color = colors.HexColor("#E2E8F0")
        
        # 1. Header
        # CAP logo
        cx, cy, r = 54 + 8, 755, 8
        self.setFillColor(blue_600)
        self.setStrokeColor(colors.transparent)
        self.circle(cx, cy, r, fill=1, stroke=0)
        self.setFillColor(colors.white)
        self.circle(cx, cy, r * 0.4, fill=1, stroke=0)
        
        # CAP text
        self.setFillColor(slate_900)
        self.setFont("Helvetica-Bold", 12)
        self.drawString(cx + 12, cy - 4, "CAP")
        
        # Report Title
        self.setFillColor(slate_900)
        self.setFont("Helvetica-Bold", 10)
        self.drawCentredString(306, cy - 3, "COGNITIVE ASSESSMENT REPORT")
        
        # Report ID details
        self.setFillColor(slate_500)
        self.setFont("Helvetica-Bold", 6.5)
        self.drawRightString(558, cy + 3, "REPORT ID")
        
        report_id_str = self.report.report_id if self.report else "CAP-2026-E363"
        self.setFillColor(blue_600)
        self.setFont("Helvetica-Bold", 8.5)
        self.drawRightString(558, cy - 6, report_id_str)
        
        # Header separator line
        self.setStrokeColor(border_color)
        self.setLineWidth(0.75)
        self.line(54, 738, 558, 738)
        
        # 2. Footer
        # Footer separator line
        self.line(54, 55, 558, 55)
        
        # Left footer text
        self.setFillColor(slate_500)
        self.setFont("Helvetica-Bold", 7)
        self.drawString(54, 42, "This report is generated by Cognitive Assessment Platform · Confidential · Clinical use only.")
        self.setFont("Helvetica", 7)
        self.drawString(54, 32, "CogHealth diagnostic standards © 2024. Does not constitute a neurological diagnosis.")
        
        # Right footer text
        self.drawRightString(558, 42, f"Page {self._pageNumber:02d} of {page_count:02d}")
        
        system_version = self.report.system_version if self.report else "2.5.0-LTS"
        self.drawRightString(558, 32, f"System Ver: {system_version}")
        
        self.restoreState()


class RoundedTable(Table):
    """Subclass of Table that draws a rounded background and border."""
    def __init__(self, data, colWidths=None, rowHeights=None, style=None, 
                 bgColor=None, borderColor=None, borderRadius=8, borderWidth=0.5, **kwargs):
        super().__init__(data, colWidths, rowHeights, style, **kwargs)
        self.bgColor = bgColor
        self.borderColor = borderColor
        self.borderRadius = borderRadius
        self.borderWidth = borderWidth

    def draw(self):
        self.canv.saveState()
        if self.bgColor:
            self.canv.setFillColor(self.bgColor)
        else:
            self.canv.setFillColor(colors.white)
            
        if self.borderColor:
            self.canv.setStrokeColor(self.borderColor)
            self.canv.setLineWidth(self.borderWidth)
        else:
            self.canv.setStrokeColor(colors.transparent)
            
        self.canv.roundRect(0, 0, self._width, self._height, self.borderRadius, 
                             fill=1 if self.bgColor else 0, 
                             stroke=1 if self.borderColor else 0)
        self.canv.restoreState()
        super().draw()


class ColorDot(Flowable):
    """Flowable that draws a small color dot."""
    def __init__(self, size, color):
        super().__init__()
        self.size = size
        self.color = color

    def wrap(self, availWidth, availHeight):
        return self.size, self.size

    def draw(self):
        self.canv.saveState()
        self.canv.setFillColor(self.color)
        self.canv.setStrokeColor(colors.transparent)
        self.canv.circle(self.size / 2, self.size / 2, self.size / 2, fill=1, stroke=0)
        self.canv.restoreState()


class ProgressBar(Flowable):
    """Flowable that draws a rounded horizontal progress bar."""
    def __init__(self, width, height, progress, color, bg_color=colors.HexColor("#F1F5F9")):
        super().__init__()
        self.width = width
        self.height = height
        self.progress = min(max(float(progress), 0.0), 1.0)
        self.color = color
        self.bg_color = bg_color

    def wrap(self, availWidth, availHeight):
        return self.width, self.height

    def draw(self):
        self.canv.saveState()
        # Track background
        self.canv.setFillColor(self.bg_color)
        self.canv.setStrokeColor(colors.transparent)
        self.canv.roundRect(0, 0, self.width, self.height, self.height / 2, fill=1, stroke=0)
        
        # Progress fill
        if self.progress > 0:
            self.canv.setFillColor(self.color)
            fill_width = self.width * self.progress
            self.canv.roundRect(0, 0, fill_width, self.height, self.height / 2, fill=1, stroke=0)
            
        self.canv.restoreState()


class CircleGauge(Flowable):
    """Flowable that draws a circular gauge with score in center."""
    def __init__(self, size, score):
        super().__init__()
        self.size = size
        self.score = score

    def wrap(self, availWidth, availHeight):
        return self.size, self.size

    def draw(self):
        cx = self.size / 2
        cy = self.size / 2
        r = self.size / 2 - 6
        
        self.canv.saveState()
        
        # 1. Background track
        self.canv.setStrokeColor(colors.HexColor("#F1F5F9"))
        self.canv.setLineWidth(8)
        self.canv.setFillColor(colors.transparent)
        self.canv.circle(cx, cy, r, fill=0, stroke=1)
        
        # 2. Progress arc
        if self.score >= 75:
            color = colors.HexColor("#0f766e")
        elif self.score >= 50:
            color = colors.HexColor("#d97706")
        else:
            color = colors.HexColor("#dc2626")
            
        self.canv.setStrokeColor(color)
        self.canv.setLineCap(1) # Rounded cap
        self.canv.setLineWidth(8)
        
        x1, y1 = cx - r, cy - r
        x2, y2 = cx + r, cy + r
        extent = -360 * (self.score / 100.0)
        if abs(extent) > 0.001:
            self.canv.arc(x1, y1, x2, y2, 90, extent)
        
        self.canv.restoreState()
        
        # 3. Score text
        self.canv.saveState()
        self.canv.setFont("Helvetica-Bold", 24)
        self.canv.setFillColor(colors.HexColor("#1E293B"))
        self.canv.drawCentredString(cx, cy - 4, f"{self.score}")
        
        self.canv.setFont("Helvetica-Bold", 8)
        self.canv.setFillColor(colors.HexColor("#64748B"))
        self.canv.drawCentredString(cx, cy - 16, "/ 100")
        self.canv.restoreState()


class DomainDonutChart(Flowable):
    """Flowable that draws a 5-domain ring donut."""
    def __init__(self, size):
        super().__init__()
        self.size = size
        self.colors = [
            colors.HexColor("#2563EB"), # Attention (Blue)
            colors.HexColor("#7C3AED"), # Memory (Purple)
            colors.HexColor("#0D9488"), # Reasoning (Teal)
            colors.HexColor("#10B981"), # Coordination (Green)
            colors.HexColor("#D85A30"), # Perception (Orange/Red)
        ]

    def wrap(self, availWidth, availHeight):
        return self.size, self.size

    def draw(self):
        cx = self.size / 2
        cy = self.size / 2
        r = self.size / 2 - 8
        
        self.canv.saveState()
        self.canv.setLineWidth(14)
        self.canv.setLineCap(0) # Butt caps
        
        x1, y1 = cx - r, cy - r
        x2, y2 = cx + r, cy + r
        
        # 5 equal segments of 72 degrees each, with spacing
        start_angle = 90
        extent = -72
        
        for col in self.colors:
            self.canv.setStrokeColor(col)
            # 4 degrees gap by drawing -68 extent and skipping 4 degrees
            self.canv.arc(x1, y1, x2, y2, start_angle - 2, extent + 4)
            start_angle += extent
            
        self.canv.restoreState()
        
        self.canv.saveState()
        self.canv.setFont("Helvetica-Bold", 18)
        self.canv.setFillColor(colors.HexColor("#1E293B"))
        self.canv.drawCentredString(cx, cy - 3, "5")
        
        self.canv.setFont("Helvetica-Bold", 7)
        self.canv.setFillColor(colors.HexColor("#64748B"))
        self.canv.drawCentredString(cx, cy - 13, "DOMAINS")
        self.canv.restoreState()


class CardIcon(Flowable):
    """Flowable that draws custom task icons."""
    def __init__(self, size, color_hex, icon_type="circle"):
        super().__init__()
        self.size = size
        self.color_hex = color_hex
        self.icon_type = icon_type

    def wrap(self, availWidth, availHeight):
        return self.size, self.size

    def draw(self):
        self.canv.saveState()
        
        # Map primary hex to light bg hex
        bg_colors = {
            "#3b82f6": "#EFF6FF", # CPT Blue
            "#ef4444": "#FEF2F2", # Go/No-Go Red
            "#6366f1": "#F5F3FF", # N-Back Indigo
            "#10b981": "#ECFDF5", # Word Recall Emerald / Shape Match Green
            "#f59e0b": "#FEF3C7", # Updating Amber
            "#14b8a6": "#F0FDFA", # Tower Teal
            "#8b5cf6": "#F5F3FF", # Divided Attention Purple
        }
        
        fill_color = colors.HexColor(bg_colors.get(self.color_hex.lower(), "#F1F5F9"))
        self.canv.setFillColor(fill_color)
        self.canv.setStrokeColor(colors.transparent)
        self.canv.roundRect(0, 0, self.size, self.size, 4, fill=1, stroke=0)
        
        # Draw the symbol
        self.canv.setFillColor(colors.HexColor(self.color_hex))
        self.canv.setStrokeColor(colors.HexColor(self.color_hex))
        self.canv.setLineWidth(1.2)
        self.canv.setLineCap(1)
        
        cx = self.size / 2
        cy = self.size / 2
        
        if self.icon_type == "activity":
            p = self.canv.beginPath()
            p.moveTo(cx - 5, cy)
            p.lineTo(cx - 2.5, cy)
            p.lineTo(cx - 1.25, cy + 4)
            p.lineTo(cx + 1.25, cy - 4)
            p.lineTo(cx + 2.5, cy)
            p.lineTo(cx + 5, cy)
            self.canv.drawPath(p, fill=0, stroke=1)
        elif self.icon_type == "shield":
            p = self.canv.beginPath()
            p.moveTo(cx, cy + 4)
            p.lineTo(cx - 3.5, cy + 2)
            p.lineTo(cx - 3.5, cy - 2)
            p.lineTo(cx, cy - 5)
            p.lineTo(cx + 3.5, cy - 2)
            p.lineTo(cx + 3.5, cy + 2)
            p.close()
            self.canv.drawPath(p, fill=0, stroke=1)
        elif self.icon_type == "award":
            self.canv.circle(cx, cy + 2, 2.5, fill=0, stroke=1)
            p = self.canv.beginPath()
            p.moveTo(cx - 1.5, cy)
            p.lineTo(cx - 2.5, cy - 4.5)
            p.lineTo(cx, cy - 3.5)
            p.lineTo(cx + 2.5, cy - 4.5)
            p.lineTo(cx + 1.5, cy)
            self.canv.drawPath(p, fill=0, stroke=1)
        elif self.icon_type == "brain":
            self.canv.circle(cx - 1.5, cy, 2.2, fill=1, stroke=0)
            self.canv.circle(cx + 1.5, cy, 2.2, fill=1, stroke=0)
            self.canv.circle(cx, cy - 1.5, 1.8, fill=1, stroke=0)
        elif self.icon_type == "zap":
            p = self.canv.beginPath()
            p.moveTo(cx - 1, cy + 5)
            p.lineTo(cx + 2, cy + 1)
            p.lineTo(cx, cy)
            p.lineTo(cx + 1.5, cy - 5)
            p.lineTo(cx - 1.5, cy - 1)
            p.lineTo(cx + 0.5, cy)
            p.close()
            self.canv.drawPath(p, fill=1, stroke=0)
        elif self.icon_type == "layers":
            self.canv.rect(cx - 4, cy + 2, 8, 1.5, fill=1, stroke=0)
            self.canv.rect(cx - 4.5, cy - 0.5, 9, 1.5, fill=1, stroke=0)
            self.canv.rect(cx - 5, cy - 3, 10, 1.5, fill=1, stroke=0)
        elif self.icon_type == "git":
            self.canv.circle(cx - 2, cy - 3, 1.2, fill=1, stroke=0)
            self.canv.circle(cx - 2, cy + 3, 1.2, fill=1, stroke=0)
            self.canv.circle(cx + 2.5, cy, 1.2, fill=1, stroke=0)
            p = self.canv.beginPath()
            p.moveTo(cx - 2, cy - 1.8)
            p.lineTo(cx - 2, cy + 1.8)
            self.canv.drawPath(p, fill=0, stroke=1)
            p = self.canv.beginPath()
            p.moveTo(cx - 2, cy)
            p.lineTo(cx + 1.3, cy)
            self.canv.drawPath(p, fill=0, stroke=1)
        elif self.icon_type == "eye":
            self.canv.circle(cx, cy, 1.8, fill=1, stroke=0)
            p = self.canv.beginPath()
            p.moveTo(cx - 4.5, cy)
            p.curveTo(cx - 2.25, cy + 2.5, cx + 2.25, cy + 2.5, cx + 4.5, cy)
            p.curveTo(cx + 2.25, cy - 2.5, cx - 2.25, cy - 2.5, cx - 4.5, cy)
            self.canv.drawPath(p, fill=0, stroke=1)
        else:
            self.canv.circle(cx, cy, 3, fill=1, stroke=0)
            
        self.canv.restoreState()


class CheckmarkIcon(Flowable):
    """Flowable that draws a circular checkmark icon."""
    def __init__(self, size=14, color_hex="#2563EB"):
        super().__init__()
        self.size = size
        self.color_hex = color_hex

    def wrap(self, availWidth, availHeight):
        return self.size, self.size

    def draw(self):
        self.canv.saveState()
        cx = self.size / 2
        cy = self.size / 2
        r = self.size / 2 - 1
        
        # Circular background
        self.canv.setFillColor(colors.HexColor("#EFF6FF"))
        self.canv.setStrokeColor(colors.transparent)
        self.canv.circle(cx, cy, r, fill=1, stroke=0)
        
        # Checkmark paths
        self.canv.setStrokeColor(colors.HexColor(self.color_hex))
        self.canv.setLineWidth(1.5)
        self.canv.setLineCap(1)
        
        p = self.canv.beginPath()
        p.moveTo(cx - 3, cy - 0.5)
        p.lineTo(cx - 0.8, cy - 2.7)
        p.lineTo(cx + 3.2, cy + 2.3)
        self.canv.drawPath(p, fill=0, stroke=1)
        
        self.canv.restoreState()


class PDFGenerator:
    def get_status_styles(self, score):
        """Get score classification styles."""
        if score >= 75:
            return "Above Average", colors.HexColor("#0f766e"), colors.HexColor("#E6F4F2")
        elif score >= 50:
            return "Average", colors.HexColor("#d97706"), colors.HexColor("#FEF3C7")
        else:
            return "Below Average", colors.HexColor("#dc2626"), colors.HexColor("#FEE2E2")

    def generate_report_pdf(self, report: Report) -> bytes:
        """Compile a premium single-page clinical PDF report using ReportLab."""
        buffer = io.BytesIO()
        
        # Page size: letter (612 x 792 pt). Margins 0.75 inch (54 pt) left/right, 0.75 inch (54 pt) top/bottom
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
        )
        
        styles = getSampleStyleSheet()
        
        # Setup Paragraph styles
        styles.add(ParagraphStyle(
            name="PatientKey",
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor("#64748B"),
        ))
        
        styles.add(ParagraphStyle(
            name="PatientVal",
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#1E293B"),
        ))
        
        styles.add(ParagraphStyle(
            name="SectionHeading",
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#1E293B"),
            spaceBefore=12,
            spaceAfter=6,
            keepWithNext=True,
        ))

        styles.add(ParagraphStyle(
            name="SectionHeadingCenter",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#64748B"),
            alignment=1, # Center
            spaceAfter=6,
            keepWithNext=True,
        ))

        styles.add(ParagraphStyle(
            name="DomainLabel",
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#1E293B"),
        ))

        styles.add(ParagraphStyle(
            name="PillText",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            alignment=1,
        ))

        styles.add(ParagraphStyle(
            name="LegendText",
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=9,
            textColor=colors.HexColor("#1E293B"),
        ))

        styles.add(ParagraphStyle(
            name="CardTitle",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#1E293B"),
        ))

        styles.add(ParagraphStyle(
            name="MetricLabel",
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=10,
            textColor=colors.HexColor("#64748B"),
        ))

        styles.add(ParagraphStyle(
            name="MetricVal",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#1E293B"),
            alignment=2,
        ))

        styles.add(ParagraphStyle(
            name="RecText",
            fontName="Helvetica",
            fontSize=7.5,
            leading=10.5,
            textColor=colors.HexColor("#475569"),
        ))

        styles.add(ParagraphStyle(
            name="TableLabel",
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#334155"),
        ))

        styles.add(ParagraphStyle(
            name="TableVal",
            fontName="Helvetica",
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#475569"),
        ))

        domain_colors = {
            "Attention": "#2563EB",
            "Memory": "#7C3AED",
            "Reasoning": "#0D9488",
            "Coordination": "#10B981",
            "Perception": "#D85A30",
        }
        for name, col in domain_colors.items():
            styles.add(ParagraphStyle(
                name=f"DomainScore_{name}",
                fontName="Helvetica-Bold",
                fontSize=9,
                leading=11,
                textColor=colors.HexColor(col),
                alignment=2,
            ))
            
        story = []
        
        # 1. Spacer below running header
        story.append(Spacer(1, 10))
        
        # 2. Patient Details Grid
        created_date = report.created_at
        if isinstance(created_date, str):
            try:
                created_date = datetime.fromisoformat(created_date.replace("Z", "+00:00"))
            except Exception:
                created_date = datetime.now()
        if not isinstance(created_date, (datetime, date)):
            created_date = datetime.now()
        formatted_date = created_date.strftime("%B %d, %Y")
        
        gender_val = report.patient_gender.value if hasattr(report.patient_gender, "value") else str(report.patient_gender)
        
        left_meta = Table([
            [Paragraph("PATIENT", styles["PatientKey"]), Paragraph(report.patient_name, styles["PatientVal"])],
            [Paragraph("AGE / SEX", styles["PatientKey"]), Paragraph(f"{report.patient_age} years / {gender_val}", styles["PatientVal"])],
            [Paragraph("PHONE", styles["PatientKey"]), Paragraph(report.patient_phone, styles["PatientVal"])],
        ], colWidths=[80, 162])
        left_meta.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'BASELINE'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 2),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2),
        ]))
        
        right_meta = Table([
            [Paragraph("DATE ISSUED", styles["PatientKey"]), Paragraph(formatted_date, styles["PatientVal"])],
            [Paragraph("CLINICIAN", styles["PatientKey"]), Paragraph(report.clinician_name, styles["PatientVal"])],
            [Paragraph("ASSESSMENT ID", styles["PatientKey"]), Paragraph(str(report.session_id)[:8] + "...", styles["PatientVal"])],
        ], colWidths=[100, 142])
        right_meta.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'BASELINE'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 2),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2),
        ]))
        
        meta_table = Table([[left_meta, "", right_meta]], colWidths=[242, 20, 242])
        meta_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(meta_table)
        
        patient_separator = Table([[""]], colWidths=[504])
        patient_separator.setStyle(TableStyle([
            ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2),
            ('TOPPADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(patient_separator)
        story.append(Spacer(1, 10))
        
        # 3. Domain distribution Section
        story.append(Paragraph("DOMAIN DISTRIBUTION", styles["SectionHeadingCenter"]))
        
        # Column 1 contents: Overall Score Gauge + Pill status
        status_text, status_color, status_bg_color = self.get_status_styles(report.total_score)
        pill_table = RoundedTable(
            [[Paragraph(f"<font color='{status_color.hexval()}'><b>{status_text}</b></font>", styles["PillText"])]],
            colWidths=[85],
            bgColor=status_bg_color,
            borderColor=colors.HexColor(status_color.hexval() + "33"),
            borderRadius=10,
            borderWidth=0.5
        )
        pill_table.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 2),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ]))
        
        col1_content = Table([
            [CircleGauge(100, report.total_score)],
            [Spacer(1, 4)],
            [pill_table]
        ], colWidths=[140])
        col1_content.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        
        # Column 2 contents: Donut Chart
        col2_content = Table([[DomainDonutChart(100)]], colWidths=[164])
        col2_content.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        
        # Column 3 contents: Domain score list
        domain_rows_data = []
        domains = [
            ("Attention", report.score_attention or 0, colors.HexColor("#2563EB")),
            ("Memory", report.score_memory or 0, colors.HexColor("#7C3AED")),
            ("Reasoning", report.score_reasoning or 0, colors.HexColor("#0D9488")),
            ("Coordination", report.score_coordination or 0, colors.HexColor("#10B981")),
            ("Perception", report.score_perception or 0, colors.HexColor("#D85A30")),
        ]
        
        for name, score, col in domains:
            name_table = Table([[ColorDot(5, col), Paragraph(name, styles["DomainLabel"])]], colWidths=[12, 138])
            name_table.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('LEFTPADDING', (0,0), (-1,-1), 0),
                ('RIGHTPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (-1,-1), 0),
                ('BOTTOMPADDING', (0,0), (-1,-1), 0),
            ]))
            
            row_header = Table([[name_table, Paragraph(f"{score}%", styles[f"DomainScore_{name}"])]], colWidths=[150, 50])
            row_header.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('LEFTPADDING', (0,0), (-1,-1), 0),
                ('RIGHTPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (-1,-1), 0),
                ('BOTTOMPADDING', (0,0), (-1,-1), 0),
            ]))
            
            domain_rows_data.append([row_header])
            domain_rows_data.append([Spacer(1, 2)])
            domain_rows_data.append([ProgressBar(width=200, height=4, progress=score/100.0, color=col)])
            domain_rows_data.append([Spacer(1, 6)])
            
        if domain_rows_data:
            domain_rows_data.pop() # Remove trailing space
            
        col3_content = Table(domain_rows_data, colWidths=[200])
        col3_content.setStyle(TableStyle([
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        
        # Domain distribution main table
        distribution_table = Table([[col1_content, col2_content, col3_content]], colWidths=[140, 164, 200])
        distribution_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(distribution_table)
        story.append(Spacer(1, 10))
        
        # 4. Legend bands table
        legend_cells = [
            [
                Table([[ColorDot(6, colors.HexColor("#0f766e")), Paragraph("Above Average <font color='#64748B'>(75 – 100)</font>", styles["LegendText"])]], colWidths=[12, 138]),
                Table([[ColorDot(6, colors.HexColor("#d97706")), Paragraph("Average <font color='#64748B'>(50 – 74)</font>", styles["LegendText"])]], colWidths=[12, 138]),
                Table([[ColorDot(6, colors.HexColor("#dc2626")), Paragraph("Below Average <font color='#64748B'>(0 – 49)</font>", styles["LegendText"])]], colWidths=[12, 138])
            ]
        ]
        
        legend_inner = Table(legend_cells, colWidths=[168, 168, 168])
        legend_inner.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        
        legend_table = RoundedTable(
            [[legend_inner]],
            colWidths=[504],
            bgColor=colors.HexColor("#F8FAFC"),
            borderColor=colors.HexColor("#E2E8F0"),
            borderRadius=8,
            borderWidth=0.5
        )
        legend_table.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(legend_table)
        story.append(Spacer(1, 10))
        
        # 5. Detailed Clinical Metrics Cards Grid
        story.append(Paragraph("DETAILED CLINICAL METRICS", styles["SectionHeading"]))
        
        c_metrics = report.clinical_metrics or {}
        
        def get_task_val(task_id, key, suffix="", scale=1):
            val = c_metrics.get(task_id, {}).get(key)
            if val is None:
                return "N/A"
            numeric_val = float(val) * scale
            if numeric_val % 1 == 0:
                formatted_val = f"{int(numeric_val)}"
            else:
                formatted_val = f"{numeric_val:.1f}"
            return f"{formatted_val}{suffix}"

        def make_metric_card(title, icon_type, color_hex, metrics):
            header_table = Table([[CardIcon(18, color_hex, icon_type), Paragraph(title, styles["CardTitle"])]], colWidths=[20, 134])
            header_table.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('LEFTPADDING', (0,0), (-1,-1), 0),
                ('RIGHTPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (-1,-1), 0),
                ('BOTTOMPADDING', (0,0), (-1,-1), 0),
            ]))
            
            card_rows = [[header_table], [Spacer(1, 3)]]
            
            metrics_data = []
            for label, val in metrics:
                metrics_data.append([
                    Paragraph(label, styles["MetricLabel"]),
                    Paragraph(val, styles["MetricVal"])
                ])
            
            metrics_table = Table(metrics_data, colWidths=[104, 50])
            metrics_table.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('ALIGN', (1,0), (1,-1), 'RIGHT'),
                ('LEFTPADDING', (0,0), (-1,-1), 0),
                ('RIGHTPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (-1,-1), 1.5),
                ('BOTTOMPADDING', (0,0), (-1,-1), 1.5),
            ]))
            
            card_rows.append([metrics_table])
            
            card_content_table = Table(card_rows, colWidths=[154])
            card_content_table.setStyle(TableStyle([
                ('LEFTPADDING', (0,0), (-1,-1), 0),
                ('RIGHTPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (-1,-1), 0),
                ('BOTTOMPADDING', (0,0), (-1,-1), 0),
            ]))
            
            card = RoundedTable(
                [[card_content_table]],
                colWidths=[162],
                bgColor=colors.HexColor("#F8FAFC"),
                borderColor=colors.HexColor("#E2E8F0"),
                borderRadius=10,
                borderWidth=0.5
            )
            card.setStyle(TableStyle([
                ('TOPPADDING', (0,0), (-1,-1), 6),
                ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                ('LEFTPADDING', (0,0), (-1,-1), 8),
                ('RIGHTPADDING', (0,0), (-1,-1), 8),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ]))
            return card

        cpt_card = make_metric_card(
            "Sustained Attention (CPT)", "activity", "#3B82F6",
            [
                ("Accuracy", get_task_val("cpt", "accuracy", "%")),
                ("Reaction Time", get_task_val("cpt", "reactionTime", " ms")),
                ("Vigilance Drop", get_task_val("cpt", "vigilanceDrop", "%")),
            ]
        )
        
        gng_card = make_metric_card(
            "Impulsivity (Go/No-Go)", "shield", "#EF4444",
            [
                ("Accuracy", get_task_val("go-no-go", "accuracy", "%")),
                ("Commission Errors", get_task_val("go-no-go", "commissionErrors")),
                ("Inhibitory Control Index", get_task_val("go-no-go", "inhibitoryControlIndex", "%", 100)),
            ]
        )
        
        nbk_card = make_metric_card(
            "Working Memory (N-Back)", "award", "#6366F1",
            [
                ("Accuracy", get_task_val("n-back", "accuracy", "%")),
                ("N-Back Level Achieved", get_task_val("n-back", "nBackLevel")),
            ]
        )
        
        wr_card = make_metric_card(
            "Word Recall (Memory)", "brain", "#10B981",
            [
                ("Accuracy", get_task_val("word-recall", "accuracy", "%")),
                ("Retention Score", get_task_val("word-recall", "retentionScore", "%", 100)),
                ("Intrusion Errors", get_task_val("word-recall", "intrusionErrors")),
            ]
        )
        
        upd_card = make_metric_card(
            "Updating", "zap", "#F59E0B",
            [
                ("Accuracy", get_task_val("updating", "accuracy", "%")),
                ("Updating Efficiency", get_task_val("updating", "updatingEfficiency", "%", 100)),
            ]
        )
        
        twr_card = make_metric_card(
            "Executive Functioning (Tower)", "layers", "#14B8A6",
            [
                ("Efficiency Score", get_task_val("tower-puzzle", "efficiencyScore", "%", 100)),
                ("Planning Time", get_task_val("tower-puzzle", "planningTimeMs", " sec", 0.001)),
            ]
        )
        
        da_card = make_metric_card(
            "Divided Attention", "git", "#8B5CF6",
            [
                ("Primary Accuracy", get_task_val("divided-attention", "primaryAccuracy", "%")),
                ("Secondary Accuracy", get_task_val("divided-attention", "secondaryAccuracy", "%")),
                ("Interference Score", get_task_val("divided-attention", "interferenceScore", "%")),
                ("Visual Dual-Task Cost", get_task_val("divided-attention", "dualTaskCostVisual", "%")),
                ("Auditory Dual-Task Cost", get_task_val("divided-attention", "dualTaskCostAuditory", "%")),
                ("Reaction Time Variability", get_task_val("divided-attention", "rtVariability", " ms")),
            ]
        )
        
        sm_card = make_metric_card(
            "Shape Match (Perception)", "eye", "#10B981",
            [
                ("Accuracy", get_task_val("shape-match", "accuracy", "%")),
                ("Reaction Time", get_task_val("shape-match", "reactionTime", " ms")),
                ("Commission Errors", get_task_val("shape-match", "commissionErrors")),
            ]
        )

        metrics_grid_data = [
            [cpt_card, "", gng_card, "", nbk_card],
            ["", "", "", "", ""],
            [wr_card, "", upd_card, "", twr_card],
            ["", "", "", "", ""],
            [da_card, "", sm_card, "", ""]
        ]
        
        metrics_grid_table = Table(
            metrics_grid_data,
            colWidths=[162, 9, 162, 9, 162],
            rowHeights=[82, 6, 82, 6, 82]
        )
        metrics_grid_table.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(metrics_grid_table)
        story.append(Spacer(1, 10))
        
        # 6. Clinical Recommendations Section
        recommendations = report.recommendations
        if not recommendations:
            recommendations = [
                "Engage in high-frequency word puzzles and strategic memory games (minimum 15 mins daily) to stimulate the temporal lobe functions.",
                "Maintain a consistent sleep hygiene schedule with 7.5 to 8 hours of restorative rest to optimize memory consolidation processes.",
                "Incorporate light physical activity, such as brisk walking or yoga, 3 times a week to improve cerebral blood flow and coordination metrics.",
                "Schedule a 6-month clinical re-assessment to monitor progress in the Reasoning and Memory domains for longitudinal comparative analysis."
            ]
            
        def make_rec_card(rec_list):
            if not rec_list:
                return Spacer(1, 1)
            rows = []
            for rec in rec_list:
                rows.append([
                    CheckmarkIcon(12, "#2563EB"),
                    Paragraph(rec, styles["RecText"])
                ])
                rows.append(["", Spacer(1, 4)])
            if rows:
                rows.pop()
                
            rec_inner_table = Table(rows, colWidths=[16, 215])
            rec_inner_table.setStyle(TableStyle([
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('LEFTPADDING', (0,0), (-1,-1), 0),
                ('RIGHTPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (-1,-1), 0),
                ('BOTTOMPADDING', (0,0), (-1,-1), 0),
            ]))
            
            card = RoundedTable(
                [[rec_inner_table]],
                colWidths=[247],
                bgColor=colors.white,
                borderColor=colors.HexColor("#E2E8F0"),
                borderRadius=12,
                borderWidth=0.5
            )
            card.setStyle(TableStyle([
                ('TOPPADDING', (0,0), (-1,-1), 8),
                ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                ('LEFTPADDING', (0,0), (-1,-1), 8),
                ('RIGHTPADDING', (0,0), (-1,-1), 8),
            ]))
            return card

        col1_items = recommendations[:(len(recommendations)+1)//2]
        col2_items = recommendations[(len(recommendations)+1)//2:]
        
        col1_card = make_rec_card(col1_items)
        col2_card = make_rec_card(col2_items)
        
        recs_table = Table([[col1_card, "", col2_card]], colWidths=[247, 10, 247])
        recs_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        
        story.append(Paragraph("Clinical Recommendations", styles["SectionHeading"]))
        story.append(recs_table)
        
        # 7. Optional Clinical Screening Scales (PHQ-9, GAD-7, PSS-10)
        has_questionnaire = any(x is not None for x in [report.phq9_score, report.gad7_score, report.pss10_score, getattr(report, 'araq_score', None)])
        if has_questionnaire:
            story.append(Spacer(1, 10))
            story.append(Paragraph("Clinical Screening Scales", styles["SectionHeading"]))
            
            q_rows = [[
                Paragraph("<b>Scale Name</b>", styles["TableLabel"]),
                Paragraph("<b>Total Score</b>", styles["TableLabel"]),
                Paragraph("<b>Clinical Interpretation</b>", styles["TableLabel"]),
            ]]
            
            if report.phq9_score is not None:
                val = report.phq9_score
                if val >= 15:
                    interp, t_col = "Moderately Severe to Severe Depression", "#dc2626"
                elif val >= 10:
                    interp, t_col = "Moderate Depression", "#d97706"
                elif val >= 5:
                    interp, t_col = "Mild Depression", "#0f766e"
                else:
                    interp, t_col = "Minimal / Subclinical", "#0f766e"
                q_rows.append([
                    Paragraph("PHQ-9 (Depressive Symptomatology)", styles["TableVal"]),
                    Paragraph(f"<b>{val}</b> / 27", styles["TableVal"]),
                    Paragraph(f"<font color='{t_col}'><b>{interp}</b></font>", styles["TableVal"]),
                ])
                
            if report.gad7_score is not None:
                val = report.gad7_score
                if val >= 15:
                    interp, t_col = "Severe Anxiety", "#dc2626"
                elif val >= 10:
                    interp, t_col = "Moderate Anxiety", "#d97706"
                elif val >= 5:
                    interp, t_col = "Mild Anxiety", "#0f766e"
                else:
                    interp, t_col = "Minimal / Subclinical", "#0f766e"
                q_rows.append([
                    Paragraph("GAD-7 (Generalized Anxiety Scale)", styles["TableVal"]),
                    Paragraph(f"<b>{val}</b> / 21", styles["TableVal"]),
                    Paragraph(f"<font color='{t_col}'><b>{interp}</b></font>", styles["TableVal"]),
                ])

            if report.pss10_score is not None:
                val = report.pss10_score
                if val >= 27:
                    interp, t_col = "High Perceived Stress", "#dc2626"
                elif val >= 14:
                    interp, t_col = "Moderate Perceived Stress", "#d97706"
                else:
                    interp, t_col = "Low Perceived Stress", "#0f766e"
                q_rows.append([
                    Paragraph("PSS-10 (Perceived Stress Scale)", styles["TableVal"]),
                    Paragraph(f"<b>{val}</b> / 40", styles["TableVal"]),
                    Paragraph(f"<font color='{t_col}'><b>{interp}</b></font>", styles["TableVal"]),
                ])

            if getattr(report, 'araq_score', None) is not None:
                val = report.araq_score
                
                def get_sec_severity(score: int, section: str) -> str:
                    if section == "A":
                        if score >= 25: return "Severe"
                        if score >= 17: return "Moderate"
                        if score >= 9: return "Mild"
                        return "Minimal"
                    elif section == "B":
                        if score >= 19: return "Severe"
                        if score >= 13: return "Moderate"
                        if score >= 7: return "Mild"
                        return "Minimal"
                    elif section == "C":
                        if score >= 25: return "Severe"
                        if score >= 17: return "Moderate"
                        if score >= 9: return "Mild"
                        return "Minimal"
                    elif section == "D":
                        if score >= 13: return "Severe"
                        if score >= 9: return "Moderate"
                        if score >= 5: return "Mild"
                        return "Minimal"
                    return "Minimal"
                
                sec_a = report.araq_sec_a_score or 0
                sec_b = report.araq_sec_b_score or 0
                sec_c = report.araq_sec_c_score or 0
                sec_d = report.araq_sec_d_score or 0
                
                sec_a_interp = get_sec_severity(sec_a, "A")
                sec_b_interp = get_sec_severity(sec_b, "B")
                sec_c_interp = get_sec_severity(sec_c, "C")
                sec_d_interp = get_sec_severity(sec_d, "D")
                
                # Clinical interpretation based on section profiles
                high_a = sec_a >= 17
                high_b = sec_b >= 13
                high_c = sec_c >= 17
                
                if high_a and high_b and high_c:
                    overall_interp = "Mixed ADHD + Anxiety Type"
                    t_col = "#dc2626"
                elif high_a and not high_b and not high_c:
                    overall_interp = "Predominant ADHD-Type Executive Dysfunction"
                    t_col = "#d97706"
                elif high_b and not high_a:
                    overall_interp = "Predominant Anticipatory Anxiety"
                    t_col = "#d97706"
                elif high_c and not high_a and not high_b:
                    overall_interp = "Predominant Fear of Failure / Perfectionism"
                    t_col = "#d97706"
                else:
                    parts = []
                    if high_a: parts.append("Executive Dysfunction")
                    if high_b: parts.append("Anticipatory Anxiety")
                    if high_c: parts.append("Fear of Failure")
                    if parts:
                        overall_interp = "Elevated " + " & ".join(parts)
                        t_col = "#d97706"
                    else:
                        overall_interp = "Minimal / Subclinical Avoidance & Anxiety"
                        t_col = "#0f766e"
                
                interpretation_html = (
                    f"<font color='{t_col}'><b>{overall_interp}</b></font><br/>"
                    f"• Executive Dysfunction: {sec_a}/32 ({sec_a_interp})<br/>"
                    f"• Anticipatory Anxiety: {sec_b}/24 ({sec_b_interp})<br/>"
                    f"• Fear of Failure: {sec_c}/32 ({sec_c_interp})<br/>"
                    f"• Functional Impact: {sec_d}/16 ({sec_d_interp})"
                )
                
                q_rows.append([
                    Paragraph("ARAQ (ADHD-Related Avoidance & Anxiety)", styles["TableVal"]),
                    Paragraph(f"<b>{val}</b> / 104", styles["TableVal"]),
                    Paragraph(interpretation_html, styles["TableVal"]),
                ])
                
            q_table = Table(q_rows, colWidths=[200, 100, 204])
            q_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(q_table)

        # Build doc using our custom NumberedCanvas
        doc.build(story, canvasmaker=lambda *args, **kwargs: NumberedCanvas(*args, report=report, **kwargs))
        
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

pdf_generator = PDFGenerator()
