from typing import Any, List, Optional
from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException, Query, Request, Response, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db, get_current_doctor
from app.models.models import Doctor, AuditLog
from app.models.enums import AuditActorType, AuditAction
from app.repositories.report import report_repo
from app.schemas.report import ReportResponse, ReportGenerateRequest
from app.services.report_service import report_service
from app.services.pdf_generator import pdf_generator

router = APIRouter()


@router.get("/", response_model=List[ReportResponse])
async def list_reports(
    db: AsyncSession = Depends(get_db),
    current_doctor: Doctor = Depends(get_current_doctor),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=100),
    search: Optional[str] = Query(None),
) -> Any:
    """List clinical reports generated by the doctor."""
    reports = await report_repo.list_by_doctor(
        db, doctor_id=current_doctor.id, skip=skip, limit=limit, search_query=search
    )
    return reports


@router.post("/generate", response_model=ReportResponse, status_code=status.HTTP_201_CREATED)
async def generate_report_from_session(
    payload: ReportGenerateRequest,
    request: Request,
    db: AsyncSession = Depends(get_db),
    current_doctor: Doctor = Depends(get_current_doctor),
) -> Any:
    """Generate clinical scores and compile a diagnostic report for a completed session."""
    ip_address = request.client.host if request.client else None
    
    # Generate the report (internally enforces status = 'completed' check)
    report = await report_service.generate_report(db, session_id=payload.session_id, ip_address=ip_address)
    
    # Double check permissions (ensure report belongs to this doctor)
    if report.doctor_id != current_doctor.id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You are not authorized to view this session's report"
        )
        
    return report


async def verify_report_access(
    db: AsyncSession,
    report_id: UUID,
    token: Optional[str],
    request: Request,
    patient_id: Optional[UUID] = None,
) -> tuple[Any, str, UUID]:
    # 1. Try patient token auth via session token_hash lookup.
    #    This works even after assessment_token_used=True because we look up
    #    the session by its stored token_hash rather than re-authenticating the raw token.
    if token:
        try:
            token_report = await report_repo.get_by_session_token_hash(db, raw_token=token)
            if token_report and token_report.id == report_id:
                return token_report, "patient", token_report.patient_id
        except Exception:
            pass

    # 2. Fetch the report to validate it exists before checking other auth methods
    report = await report_repo.get(db, id=report_id)
    if not report:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report not found"
        )

    # 3. Try patient_id-based access (patient portal: logged-in via OTP, no URL token)
    if patient_id and report.patient_id == patient_id:
        return report, "patient", patient_id

    # 4. Try doctor JWT auth
    jwt_token = None
    auth_header = request.headers.get("Authorization")
    if auth_header and auth_header.startswith("Bearer "):
        jwt_token = auth_header.split(" ")[1]
    else:
        jwt_token = request.query_params.get("auth_token")

    if jwt_token:
        try:
            from app.core.security import decode_access_token
            from app.repositories.doctor import doctor_repo
            doctor_id_str = decode_access_token(jwt_token)
            if doctor_id_str:
                doctor = await doctor_repo.get(db, id=UUID(doctor_id_str))
                if doctor and doctor.is_active and report.doctor_id == doctor.id:
                    return report, "doctor", doctor.id
        except Exception:
            pass

    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Report not found or access denied"
    )


@router.get("/{id}", response_model=ReportResponse)
async def get_report_details(
    id: UUID,
    request: Request,
    token: Optional[str] = Query(None),
    patient_id: Optional[UUID] = Query(None),
    db: AsyncSession = Depends(get_db),
) -> Any:
    """Fetch profile summary and score values for a specific report."""
    report, _, _ = await verify_report_access(db, id, token, request, patient_id)
    return report


@router.get("/{id}/pdf")
async def download_report_pdf(
    id: UUID,
    request: Request,
    token: Optional[str] = Query(None),
    patient_id: Optional[UUID] = Query(None),
    auth_token: Optional[str] = Query(None),
    db: AsyncSession = Depends(get_db),
) -> Any:
    """Compile and stream the clinical report as a premium styled PDF file."""
    report, actor_type, actor_id = await verify_report_access(db, id, token, request, patient_id)

    # Compile reportLab PDF bytes
    pdf_bytes = pdf_generator.generate_report_pdf(report)
    
    # Audit log PDF download/viewing
    ip_address = request.client.host if request.client else None
    audit = AuditLog(
        actor_id=actor_id,
        actor_type=AuditActorType.DOCTOR if actor_type == "doctor" else AuditActorType.PATIENT,
        action=AuditAction.REPORT_VIEW,
        entity_type="report",
        entity_id=id,
        metadata={"report_ref": report.report_id, "format": "pdf"},
        ip_address=ip_address,
    )
    db.add(audit)
    
    # Return as StreamingResponse
    import io
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename=cap-report-{report.report_id}.pdf"
        },
    )


@router.post("/{id}/archive", response_model=ReportResponse)
async def archive_report(
    id: UUID,
    db: AsyncSession = Depends(get_db),
    current_doctor: Doctor = Depends(get_current_doctor),
) -> Any:
    """Soft-archive a report, removing it from main clinical indexes."""
    report = await report_repo.get(db, id=id)
    if not report or report.doctor_id != current_doctor.id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report not found or access denied"
        )

    report.is_archived = True
    db.add(report)
    await db.flush()
    return report
